name: grupo-primo

services:
  postgres:
    image: postgres:alpine3.20
    container_name: postgres
    restart: always
    env_file:
      - ./../.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  application:
    container_name: application
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./../.env
    volumes:
      - application:/var/lib/application/data
    ports:
      - 4000:4000

volumes:
  postgres:
    name: volume-postgres
  application:
    name: volume-application
